---
# tasks file for perfsonar-psconfig

# Configure the measurements from remote templates
- name: Add or replace psconfig remotes
  command: psconfig publish "{{ item }}"
  with_items: "{{ perfsonar_psconfig_publish | default([]) }}"
